# Docker Compose
version: '3'

services:
  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      # See the "Environment Variables" section of the Postgres Docker library
      # guide: https://hub.docker.com/_/postgres/
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=examplepassword

  # This is the application itself.
  address-api:
    depends_on:
      - postgres
    # build the current directoroy
    build:
      context: ./address-api
      dockerfile: Dockerfile.development
    # Map the current directory to /app in the container
    volumes:
      - ./address-api:/app
    # localhost:8020
    ports:
      - '3000:3000'
    # We make these adjustments to allow for Bybug, pry, etc., per:
    # http://stackoverflow.com/questions/35211638/how-to-debug-a-rails-app-in-docker-with-pry
    tty: true
    stdin_open: true
    command: 'bundle exec puma -C config/puma.rb'
    links:
      - postgres
    environment:
      - PG_USERNAME=postgres
      - PG_PASSWORD=examplepassword

  front-end:
    # build the current directoroy
    build:
      context: ./front-end
      dockerfile: Dockerfile.development
    # Map the current directory to /var-dashboard in the container
    volumes:
      - ./front-end:/app
    # localhost:8080
    ports:
      - '8000:8000'
    # We make these adjustments to allow for Bybug, pry, etc., per:
    # http://stackoverflow.com/questions/35211638/how-to-debug-a-rails-app-in-docker-with-pry
    tty: true
    stdin_open: true
    depends_on:
      - address-api
    links:
      - address-api

volumes:
  postgres:
  address-api:
  front-end:
